---
dist: xenial
sudo: required

language: python
python:
  - "3.7"

before_install:
  - git clone https://github.com/nycrecords/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - poetry install
  - ansible --version
  - ansible-lint --version

script:
  - yamllint . -c .yamllint
  - ansible-lint . -c .ansible-lint
  - molecule --debug create -s aws
  - molecule --debug converge -s aws
  - molecule --debug verify -s aws
  - molecule --debug destroy -s aws

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
