---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - ansible-lint --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

Lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - yamllint . -c .yamllint
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws