---
dist: xenial
sudo: required

language: python
python:
  - "2.7"

before_install:
  - git clone https://github.com/nycrecords/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - pip install pipenv
  - pipenv install
  - ansible --version
  - ansible-lint --version

script:
  - cookiecutter --no-input .
  - cd ansible-role-default_role
  - yamllint . -c .yamllint
  - ansible-lint . -c .ansible-lint
